### ISSUE TITLE
Call to undefined function Benwilkins\FCM\resolve() after upgrade to Lumen 5.7

### ISSUE THREAD

**Issue by chimit** [benwilkins/laravel-fcm-notification#25]
After upgrade to Lumen 5.7 I started receiving these messagse:
```
Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function Benwilkins\FCM\resolve() in /var/www/social/vendor/benwilkins/laravel-fcm-notification/src/FcmNotificationServiceProvider.php:21
Stack trace:
#0 /var/www/social/vendor/illuminate/support/Manager.php(110): Benwilkins\FCM\FcmNotificationServiceProvider->Benwilkins\FCM\{closure}(Object(Laravel\Lumen\Application))
#1 /var/www/social/vendor/illuminate/support/Manager.php(91): Illuminate\Support\Manager->callCustomCreator('fcm')
#2 /var/www/social/vendor/illuminate/notifications/ChannelManager.php(138): Illuminate\Support\Manager->createDriver('fcm')
#3 /var/www/social/vendor/illuminate/support/Manager.php(71): Illuminate\Notifications\ChannelManager->createDriver('fcm')
#4 /var/www/social/vendor/illuminate/notifications/NotificationSender.php(144): Illuminate\Support\Manager->driver('fcm')
#5 /var/www/social/vendor/illuminate/notifications/NotificationSender.php(103): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(App\Models\Device), 'd148f571-20c9-4...', Object(App\Notifications\MessageCreated), 'fcm')
#6 /var/www/social/vendor/illuminate/support/Traits/Localizable.php(19): Illuminate\Notifications\NotificationSender->Illuminate\Notifications\{closure}()
#7 /var/www/social/vendor/illuminate/notifications/NotificationSender.php(105): Illuminate\Notifications\NotificationSender->withLocale(NULL, Object(Closure))
#8 /var/www/social/vendor/illuminate/notifications/NotificationSender.php(77): Illuminate\Notifications\NotificationSender->sendNow(Object(Illuminate\Support\Collection), Object(App\Notifications\MessageCreated))
#9 /var/www/social/vendor/illuminate/notifications/ChannelManager.php(42): Illuminate\Notifications\NotificationSender->send(Object(Illuminate\Support\Collection), Object(App\Notifications\MessageCreated))
#10 /var/www/social/vendor/illuminate/support/Facades/Facade.php(223): Illuminate\Notifications\ChannelManager->send(Object(Illuminate\Support\Collection), Object(App\Notifications\MessageCreated))
#11 /var/www/social/app/Listeners/MessageCreated.php(41): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#12 [internal function]: App\Listeners\MessageCreatedListener->handle(Object(App\Events\MessageCreated))
#13 /var/www/social/vendor/illuminate/events/CallQueuedListener.php(86): call_user_func_array(Array, Array)
#14 [internal function]: Illuminate\Events\CallQueuedListener->handle(Object(Laravel\Lumen\Application))
#15 /var/www/social/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#16 /var/www/social/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#17 /var/www/social/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#18 /var/www/social/vendor/illuminate/container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#19 /var/www/social/vendor/illuminate/bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#20 /var/www/social/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Illuminate\Events\CallQueuedListener))
#21 /var/www/social/vendor/illuminate/pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Events\CallQueuedListener))
#22 /var/www/social/vendor/illuminate/bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 /var/www/social/vendor/illuminate/queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Illuminate\Events\CallQueuedListener), false)
#24 /var/www/social/vendor/illuminate/queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#25 /var/www/social/vendor/illuminate/queue/Worker.php(327): Illuminate\Queue\Jobs\Job->fire()
#26 /var/www/social/vendor/illuminate/queue/Worker.php(277): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#27 /var/www/social/vendor/illuminate/queue/Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
#28 /var/www/social/vendor/illuminate/queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#29 /var/www/social/vendor/illuminate/queue/Console/WorkCommand.php(86): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#30 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#31 /var/www/social/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#32 /var/www/social/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#33 /var/www/social/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#34 /var/www/social/vendor/illuminate/container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#35 /var/www/social/vendor/illuminate/console/Command.php(183): Illuminate\Container\Container->call(Array)
#36 /var/www/social/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#37 /var/www/social/vendor/illuminate/console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#38 /var/www/social/vendor/symfony/console/Application.php(886): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 /var/www/social/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 /var/www/social/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#41 /var/www/social/vendor/illuminate/console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 /var/www/social/vendor/laravel/lumen-framework/src/Console/Kernel.php(116): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 /var/www/social/artisan(35): Laravel\Lumen\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 {main} {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function Benwilkins\\FCM\
esolve() at /var/www/social/vendor/benwilkins/laravel-fcm-notification/src/FcmNotificationServiceProvider.php:21)
```
Apparently, was caused by this commit https://github.com/benwilkins/laravel-fcm-notification/commit/7e25a42e0a8738fc807d066d477ae2e9be206ac2

**Comment by chimit** [comment]
Fixed in 3.0.
