### ISSUE TITLE
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

### ISSUE THREAD

**Issue by yashweb3** [benwilkins/laravel-fcm-notification#45]
`composer require benwilkins/laravel-fcm-notification:dev-master`
**After running this command it will crash my project**

After that composer dump-autoload is also stopped working. 

**FYI:** This is run in Xampp, Laravel version is 5.6, PHP Version 7.1.18

Let me know if any solution for this. because it will crash my whole project. :( 

![image](https://user-images.githubusercontent.com/48712509/62515038-b96e2f80-b83e-11e9-97d3-ba4eee4b7a89.png)
![image](https://user-images.githubusercontent.com/48712509/62515123-fb977100-b83e-11e9-97c6-bd7c95d81e26.png)

Thanks

**Comment by hakimzulkufli** [comment]
Getting the same error as well upon updating and found out that it is caused by this package. Removing this packaged fixed it but obviously, I need this package to work.

```
[2019-08-15 12:43:16] local.ERROR: Class mailer does not exist {"exception":"[object] (ReflectionException(code: -1): Class mailer does not exist at C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:767)
[stacktrace]
#0 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(767): ReflectionClass->__construct('mailer')
#1 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(646): Illuminate\\Container\\Container->build('mailer')
#2 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(601): Illuminate\\Container\\Container->resolve('mailer', Array)
#3 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(734): Illuminate\\Container\\Container->make('mailer', Array)
#4 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(900): Illuminate\\Foundation\\Application->make('mailer')
#5 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(828): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#6 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(795): Illuminate\\Container\\Container->resolveDependencies(Array)
#7 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(646): Illuminate\\Container\\Container->build('Illuminate\\\\Noti...')
#8 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(601): Illuminate\\Container\\Container->resolve('Illuminate\\\\Noti...', Array)
#9 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(734): Illuminate\\Container\\Container->make('Illuminate\\\\Noti...', Array)
#10 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Notifications\\ChannelManager.php(91): Illuminate\\Foundation\\Application->make('Illuminate\\\\Noti...')
#11 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Manager.php(96): Illuminate\\Notifications\\ChannelManager->createMailDriver()
#12 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Notifications\\ChannelManager.php(131): Illuminate\\Support\\Manager->createDriver('mail')
#13 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Manager.php(71): Illuminate\\Notifications\\ChannelManager->createDriver('mail')
#14 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Manager.php(146): Illuminate\\Support\\Manager->driver()
#15 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(223): Illuminate\\Support\\Manager->__call('resolved', Array)
#16 C:\\laragon\\www\\laravel-project\\vendor\\benwilkins\\laravel-fcm-notification\\src\\FcmNotificationServiceProvider.php(24): Illuminate\\Support\\Facades\\Facade::__callStatic('resolved', Array)
#17 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(573): Benwilkins\\FCM\\FcmNotificationServiceProvider->register()
#18 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\ProviderRepository.php(75): Illuminate\\Foundation\\Application->register(Object(Benwilkins\\FCM\\FcmNotificationServiceProvider))
#19 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(548): Illuminate\\Foundation\\ProviderRepository->load(Array)
#20 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#21 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(206): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#22 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(297): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#23 C:\\laragon\\www\\laravel-project\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(120): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#24 C:\\laragon\\www\\laravel-project\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 {main}
```

This only happen with version `3.0.1` (673adf7c5d8e2005b2a3efcd92a5ff9d50978da8) because of PR #40 . For Laravel 5.6, you can only use version up to 3.0.0.
